### ISSUE TITLE
Bump up Dockerfile to CUDA 12.6 and Ubuntu 24.04

### ISSUE THREAD

**Issue by C0rn3j** [ggml-org/whisper.cpp#2380]
I am successfully using the build against newer Ubuntu 24.04 and latest CUDA 12.6.

```ini
ARG UBUNTU_VERSION=24.04
ARG CUDA_VERSION=12.6.0
```

It seems to work fine, with the exception that I had to set `LD_LIBRARY_PATH=''` due to https://github.com/ggerganov/whisper.cpp/issues/2032#issuecomment-2078881661

Here's my compose definition for completeness:

```yaml
  whisper_cpp:
#    image: ghcr.io/ggerganov/whisper.cpp:main-cuda
    image: whisper-corncuda:latest
    container_name: whisper-cpp
    ports:
      - "7777:7777"
    volumes:
      - /home/user/whisper/:/models
    restart: unless-stopped
    environment:
      LD_LIBRARY_PATH: ""
    command: "'./server -l en -m /models/ggml-large-v3-q5_0.bin --host 0.0.0.0 --port 7777'"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```
